import React from 'react';
import Controls from '../Controls/Controls'
const TheJokes = () => {
    return(
      <div>
      <Controls/>
        this'll be a flexible box of jokes pulled from the Array generated by the API
      </div>
    )
}

export default TheJokes
