import React from 'react';

const TheJokes = () => {
    return(
      <div>
        this'll be a flexible box of jokes pulled from the Array generated by the API
      </div>
    )
}

export default TheJokes
